In [1]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

In [7]:
data = pd.read_csv('C:/Users/Dosajh/Documents/Python Scripts/new_churn_data.csv')

In [4]:
import random

In [9]:
user = data['user']
data = data.drop(columns='user')

In [11]:
data.housing.value_counts()

R     9221
na    7910
O     1834
Name: housing, dtype: int64

In [13]:
data.groupby('housing')['churn'].nunique().reset_index()

  housing  churn
0       O      2
1       R      2
2      na      2

In [14]:
data = pd.get_dummies(data)

In [16]:
data

,churn,age,deposits,withdrawal,purchases_partners,purchases,cc_taken,cc_recommended,cc_disliked,cc_liked,...,zodiac_sign_Capricorn,zodiac_sign_Gemini,zodiac_sign_Leo,zodiac_sign_Libra,zodiac_sign_Pisces,zodiac_sign_Sagittarius,zodiac_sign_Scorpio,zodiac_sign_Taurus,zodiac_sign_Virgo,zodiac_sign_na
0,0,28.0,0,0,1,0,0,96,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,35.0,47,2,86,47,0,285,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,26.0,26,3,38,25,0,74,0,0,...,1,0,0,0,0,0,0,0,0,0
3,1,32.0,5,3,111,5,0,227,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,21.0,0,0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,28.0,0,0,0,0,2,47,1,0,...,0,0,0,0,0,1,0,0,0,0
6,0,23.0,1,0,87,1,0,125,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,41.0,14,0,116,13,0,217,0,0,...,0,0,0,0,0,0,0,0,1,0
8,0,20.0,0,0,135,0,0,286,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,27.0,2,1,48,2,0,127,0,0,...,0,1,0,0,0,0,0,0,0,0
10,1,24.0,6,2,24,6,0,55,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,31.0,17,2,62,17,0,180,0,0,...,0,0,0,1,0,0,0,0,0,0
12,1,21.0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,1,0,0,0,0
13,0,37.0,0,0,39,0,0,74,0,0,...,0,0,0,0,0,0,1,0,0,0
14,1,30.0,6,0,11,6,0,20,0,0,...,0,1,0,0,0,0,0,0,0,0
15,1,44.0,0,0,0,0,3,4,3,1,...,0,0,0,0,0,0,1,0,0,0
16,1,52.0,0,0,0,0,0,74,0,0,...,0,0,0,0,1,0,0,0,0,0
17,1,25.0,0,0,0,0,0,32,0,0,...,0,0,0,0,0,0,0,0,1,0
18,1,22.0,0,0,0,0,1,67,1,0,...,0,0,0,0,1,0,0,0,0,0
19,0,29.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,25.0,0,0,3,0,0,3,0,0,...,0,0,0,1,0,0,0,0,0,0
21,1,36.0,0,0,83,0,0,153,0,0,...,0,0,0,0,1,0,0,0,0,0
22,0,45.0,48,0,76,48,0,204,0,0,...,0,0,0,0,0,1,0,0,0,0
23,1,31.0,0,0,0,0,0,63,0,0,...,0,0,1,0,0,0,0,0,0,0
24,0,45.0,0,0,0,0,0,170,0,0,...,0,0,0,0,0,0,1,0,0,0
25,0,28.0,0,0,0,0,0,207,0,0,...,0,1,0,0,0,0,0,0,0,0
26,0,24.0,0,0,37,0,0,60,0,0,...,0,0,0,0,0,0,0,0,0,1
27,1,42.0,0,0,0,0,0,5,0,0,...,0,0,0,0,0,0,1,0,0,0
28,0,27.0,0,0,0,0,2,206,0,0,...,0,0,0,0,0,0,0,1,0,0
29,0,26.0,0,0,57,0,0,154,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18935,0,20.0,10,0,61,10,0,158,0,0,...,0,0,0,0,0,0,0,0,0,0
18936,0,40.0,1,0,6,1,0,2,0,0,...,0,0,0,0,0,1,0,0,0,0
18937,0,57.0,1,0,39,1,0,198,0,0,...,0,0,0,0,0,0,0,0,1,0
18938,0,36.0,2,0,84,2,0,165,0,0,...,0,0,0,1,0,0,0,0,0,0
18939,0,25.0,0,0,122,0,0,255,0,0,...,0,0,0,0,1,0,0,0,0,0
18940,1,24.0,1,0,26,1,0,175,0,0,...,0,0,0,0,0,0,0,0,1,0
18941,1,31.0,0,0,0,0,0,244,0,0,...,0,0,0,0,0,0,0,1,0,0
18942,0,24.0,3,0,50,3,0,147,0,0,...,0,0,0,0,1,0,0,0,0,0
18943,0,35.0,0,0,115,0,0,278,0,0,...,0,0,0,0,0,0,0,0,1,0
18944,0,23.0,0,0,76,0,0,245,0,0,...,0,0,0,0,0,0,0,0,0,0
18945,0,37.0,5,1,22,5,0,63,0,0,...,0,0,0,0,0,0,0,0,0,0
18946,1,27.0,0,0,0,0,0,28,0,0,...,0,0,0,1,0,0,0,0,0,0
18947,0,19.0,30,1,89,30,0,179,0,0,...,0,0,0,1,0,0,0,0,0,0
18948,1,22.0,0,0,0,0,1,146,0,0,...,0,0,0,0,0,1,0,0,0,0
18949,0,26.0,0,0,3,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
18950,0,52.0,0,0,10,0,0,203,0,0,...,0,0,1,0,0,0,0,0,0,0
18951,1,22.0,0,0,2,0,1,134,0,0,...,0,0,0,0,1,0,0,0,0,0
18952,1,33.0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18953,0,38.0,2,0,0,2,0,40,0,0,...,0,0,0,0,1,0,0,0,0,0
18954,0,25.0,0,0,0,0,0,210,0,0,...,0,0,0,0,0,0,0,0,0,0
18955,0,35.0,0,0,57,0,0,156,0,0,...,0,0,1,0,0,0,0,0,0,0
18956,0,23.0,0,0,50,0,0,152,0,0,...,0,0,1,0,0,0,0,0,0,0
18957,0,31.0,0,0,22,0,0,138,0,0,...,0,0,0,0,0,0,0,0,1,0
18958,0,29.0,1,1,70,1,0,147,0,0,...,0,0,0,0,0,0,0,0,0,0
18959,1,20.0,0,0,2,0,0,5,0,0,...,0,0,1,0,0,0,0,0,0,0
18960,0,29.0,1,1,5,1,0,5,0,0,...,0,0,0,0,0,0,1,0,0,0
18961,1,28.0,0,0,26,0,0,31,0,0,...,0,0,0,0,0,0,0,0,1,0
18962,1,24.0,0,0,0,0,0,81,0,0,...,0,0,1,0,0,0,0,0,0,0
18963,1,46.0,2,0,16,2,0,58,0,0,...,0,0,0,0,0,0,0,0,0,0
18964,1,34.0,0,0,4,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
data = data.drop(columns = ['housing_na', 'zodiac_sign_na', 'payment_type_na'])

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.drop(columns = 'churn'), data['churn'],
                                                    test_size = 0.2,
                                                    random_state = 0)

In [22]:
pos_index = y_train[y_train.values == 1].index
neg_index = y_train[y_train.values == 0].index
if len(pos_index) > len(neg_index):
    higher = pos_index
    lower = neg_index
else:
    higher = neg_index
    lower = pos_index

random.seed(0)
higher = np.random.choice(higher, size=len(lower))
lower = np.asarray(lower)
new_indexes = np.concatenate((lower, higher))

X_train = X_train.loc[new_indexes,]
y_train = y_train[new_indexes]

In [23]:
x_train=preprocessing.normalize(X_train)
x_test = preprocessing.normalize(X_test)

In [31]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [32]:
y_pred = classifier.predict(x_test)

In [37]:
from sklearn.metrics import accuracy_score

In [36]:

print("Test Data Accuracy: %0.4f" % accuracy_score(y_test, y_pred))

Test Data Accuracy: 0.6559

In [39]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("logistic reg Accuracy: %0.3f (+/- %0.3f)" % (accuracies.mean(), accuracies.std() * 2))

C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

logistic reg Accuracy: 0.660 (+/- 0.033)

In [40]:
pd.concat([pd.DataFrame(X_train.columns, columns = ["features"]),
           pd.DataFrame(np.transpose(classifier.coef_), columns = ["coef"])
           ],axis = 1)

#coefficients

                     features      coef
0                         age  1.880034
1                    deposits -0.531783
2                  withdrawal  1.712801
3          purchases_partners -2.647661
4                   purchases -0.748819
5                    cc_taken  0.758801
6              cc_recommended  1.399257
7                 cc_disliked  0.149096
8                    cc_liked  0.162033
9        cc_application_begin  1.010819
10             app_downloaded  1.749950
11                   web_user  3.570848
12                   ios_user  1.305884
13               android_user  0.545843
14          registered_phones  2.784801
15             waiting_4_loan -0.043822
16             cancelled_loan  0.495618
17              received_loan  0.430138
18              rejected_loan  0.303337
19    left_for_two_month_plus  1.371960
20         left_for_one_month  0.169568
21                reward_rate  1.446485
22                is_referred  1.579554
23                  housing_O -0.713592
24                  housing_R  2.102441
25     payment_type_Bi-Weekly  0.265258
26       payment_type_Monthly -0.529157
27  payment_type_Semi-Monthly -0.158257
28        payment_type_Weekly  1.803093
29       zodiac_sign_Aquarius -0.320198
30          zodiac_sign_Aries  0.564125
31         zodiac_sign_Cancer  0.259314
32      zodiac_sign_Capricorn  0.092571
33         zodiac_sign_Gemini -0.042128
34            zodiac_sign_Leo  0.175370
35          zodiac_sign_Libra  0.133941
36         zodiac_sign_Pisces  0.794859
37    zodiac_sign_Sagittarius  0.246018
38        zodiac_sign_Scorpio  0.161816
39         zodiac_sign_Taurus  0.196408
40          zodiac_sign_Virgo  0.296037

In [42]:
final_results = pd.concat([y_test, user], axis = 1).dropna()
final_results['predicted_churn'] = y_pred
final_results = final_results[['user', 'churn', 'predicted_churn']].reset_index(drop=True)

In [43]:
final_results

       user  churn  predicted_churn
0     20839    0.0                1
1     15359    1.0                0
2     34210    1.0                0
3     57608    1.0                1
4     11790    0.0                1
5      1826    1.0                0
6      8508    0.0                1
7     50946    1.0                1
8     50130    1.0                0
9     55422    0.0                0
10      259    1.0                1
11    17451    0.0                0
12    41909    0.0                0
13    38825    0.0                0
14    19314    1.0                1
15    26916    0.0                0
16    30614    0.0                1
17    30329    1.0                1
18    38853    0.0                1
19    15592    1.0                1
20    40888    0.0                1
21    17918    1.0                0
22    52613    0.0                0
23      725    0.0                1
24    51797    0.0                0
25     2601    0.0                0
26    33990    0.0                1
27    10006    0.0                0
28    19296    1.0                0
29    12135    1.0                0
...     ...    ...              ...
3763  64494    1.0                0
3764   1185    0.0                1
3765  17908    0.0                0
3766  52426    0.0                0
3767  41552    0.0                1
3768  52762    1.0                0
3769  35892    1.0                1
3770  28025    1.0                0
3771  55416    0.0                0
3772  14997    0.0                1
3773  25667    0.0                1
3774  44166    0.0                0
3775  50893    1.0                0
3776  10975    1.0                1
3777  38184    0.0                0
3778  31601    0.0                0
3779  31167    0.0                0
3780  51126    0.0                1
3781  58440    0.0                1
3782  65088    0.0                0
3783  26821    0.0                1
3784  25599    0.0                0
3785   3369    0.0                1
3786  33587    1.0                0
3787  22318    0.0                1
3788  67681    0.0                1
3789  49145    1.0                0
3790  47206    0.0                0
3791  22377    0.0                0
3792  47663    1.0                0

[3793 rows x 3 columns]